### ISSUE TITLE
Family tree node connector doesn't have transition.

### ISSUE THREAD

**Issue by tandrast** [dbis-uibk/relax#186]
Need to add:
```scss
transition: all 0.5s;
-webkit-transition: all 0.5s;
-moz-transition: all 0.5s;
```
To `src/calc2/components/raTreeFamilyTree.scss`:
```scss
/*Connector styles on hover*/
.tree li div.node.active + ul li::after,
.tree li div.node.active + ul li::before,
.tree li div.node.active + ul::before,
.tree li div.node.active + ul ul::before {
	border-color: #5C5C5C;
}
```
Sidenote: comment says styles on hover, however the selector is not for hover.
